### ISSUE TITLE
Generate war file to deploy the project in tomcat 8.5

### ISSUE THREAD

**Issue by ershad1** [corneil/spring-data-rest-angular-demo#1]
Hi,
I am trying a lot to run this project as a deployable war file in tomcat 8.5 but so far i am failed. could u please tell me how to do that.

e.g. generate a angulardemo.war file and deploy it in tomcat 8.5 webapps folder and try to get the web page from http://localhost:8080/angulardemo/

update: if i change the angulardemo.war to ROOT.war and delete previous ROOT folder, then it works at http://localhost:8080/

but can it make a new context like http://localhost:8080/angulardemo/

i merged common-web and web-app so that common-web dependency go away. copy the build text of common-web to web-app. and follow spring boot war generation process from spring boot reference guide.

**Comment by corneil** [comment]
Apologies. I didn't see this.
